package com.lkw1120.client.datasource.remote.response

object FakeResp {

    fun getRepoListResp() = listOf(
        RepoItemResp(
            id = 840609605,
            nodeId = "R_kgDOMhqvRQ",
            name = "github-client",
            fullName = "lkw1120/github-client",
            private = false,
            htmlUrl = "https://github.com/lkw1120/github-client",
            description = "Simple Github Client app using Jetpack Compose",
            fork = false,
            url = "https://api.github.com/repos/lkw1120/github-client",
            forksUrl = "https://api.github.com/repos/lkw1120/github-client/forks",
            keysUrl = "https://api.github.com/repos/lkw1120/github-client/keys{/key_id}",
            collaboratorsUrl = "https://api.github.com/repos/lkw1120/github-client/collaborators{/collaborator}",
            teamsUrl = "https://api.github.com/repos/lkw1120/github-client/teams",
            hooksUrl = "https://api.github.com/repos/lkw1120/github-client/hooks",
            issueEventsUrl = "https://api.github.com/repos/lkw1120/github-client/issues/events{/number}",
            eventsUrl = "https://api.github.com/repos/lkw1120/github-client/events",
            assigneesUrl = "https://api.github.com/repos/lkw1120/github-client/assignees{/user}",
            branchesUrl = "https://api.github.com/repos/lkw1120/github-client/branches{/branch}",
            tagsUrl = "https://api.github.com/repos/lkw1120/github-client/tags",
            blobsUrl = "https://api.github.com/repos/lkw1120/github-client/git/blobs{/sha}",
            gitTagsUrl = "https://api.github.com/repos/lkw1120/github-client/git/tags{/sha}",
            gitRefsUrl = "https://api.github.com/repos/lkw1120/github-client/git/refs{/sha}",
            treesUrl = "https://api.github.com/repos/lkw1120/github-client/git/trees{/sha}",
            statusesUrl = "https://api.github.com/repos/lkw1120/github-client/statuses/{sha}",
            languagesUrl = "https://api.github.com/repos/lkw1120/github-client/languages",
            stargazersUrl = "https://api.github.com/repos/lkw1120/github-client/stargazers",
            contributorsUrl = "https://api.github.com/repos/lkw1120/github-client/contributors",
            subscribersUrl = "https://api.github.com/repos/lkw1120/github-client/subscribers",
            subscriptionUrl = "https://api.github.com/repos/lkw1120/github-client/subscription",
            commitsUrl = "https://api.github.com/repos/lkw1120/github-client/commits{/sha}",
            gitCommitsUrl = "https://api.github.com/repos/lkw1120/github-client/git/commits{/sha}",
            commentsUrl = "https://api.github.com/repos/lkw1120/github-client/comments{/number}",
            issueCommentUrl = "https://api.github.com/repos/lkw1120/github-client/issues/comments{/number}",
            contentsUrl = "https://api.github.com/repos/lkw1120/github-client/contents/{+path}",
            compareUrl = "https://api.github.com/repos/lkw1120/github-client/compare/{base}...{head}",
            mergesUrl = "https://api.github.com/repos/lkw1120/github-client/merges",
            archiveUrl = "https://api.github.com/repos/lkw1120/github-client/{archive_format}{/ref}",
            downloadsUrl = "https://api.github.com/repos/lkw1120/github-client/downloads",
            issuesUrl = "https://api.github.com/repos/lkw1120/github-client/issues{/number}",
            pullsUrl = "https://api.github.com/repos/lkw1120/github-client/pulls{/number}",
            milestonesUrl = "https://api.github.com/repos/lkw1120/github-client/milestones{/number}",
            notificationsUrl = "https://api.github.com/repos/lkw1120/github-client/notifications{?since,all,participating}",
            labelsUrl = "https://api.github.com/repos/lkw1120/github-client/labels{/name}",
            releasesUrl = "https://api.github.com/repos/lkw1120/github-client/releases{/id}",
            deploymentsUrl = "https://api.github.com/repos/lkw1120/github-client/deployments",
            createdAt = "2024-08-10T06:31:36Z",
            updatedAt = "2024-08-14T19:09:25Z",
            pushedAt = "2024-08-12T09:16:31Z",
            gitUrl = "git://github.com/lkw1120/github-client.git",
            sshUrl = "git@github.com:lkw1120/github-client.git",
            cloneUrl = "https://github.com/lkw1120/github-client.git",
            svnUrl = "https://github.com/lkw1120/github-client",
            homepage = null,
            size = 633,
            stargazersCount = 0,
            watchersCount = 0,
            language = "Kotlin",
            hasIssues = true,
            hasProjects = true,
            hasDownloads = true,
            hasWiki = false,
            hasPages = false,
            hasDiscussions = false,
            forksCount = 0,
            mirrorUrl = null,
            archived = false,
            disabled = false,
            openIssuesCount = 1,
            allowForking = true,
            isTemplate = false,
            webCommitSignoffRequired = false,
            topics = null,
            visibility = "public",
            forks = 0,
            openIssues = 1,
            watchers = 0,
            defaultBranch = "main",
        )
    )

    fun getUserDetailResp() = UserDetailResp(
        login = "lkw1120",
        id = 15232122,
        nodeId = "MDQ6VXNlcjE1MjMyMTIy",
        avatarUrl = "https://avatars.githubusercontent.com/u/15232122?v=4",
        gravatarId = "",
        url = "https://api.github.com/users/lkw1120",
        htmlUrl = "https://github.com/lkw1120",
        followersUrl = "https://api.github.com/users/lkw1120/followers",
        followingUrl = "https://api.github.com/users/lkw1120/following{/otherUser}",
        gistsUrl = "https://api.github.com/users/lkw1120/gists{/gist_id}",
        starredUrl = "https://api.github.com/users/lkw1120/starred{/owner}{/repo}",
        subscriptionsUrl = "https://api.github.com/users/lkw1120/subscriptions",
        organizationsUrl = "https://api.github.com/users/lkw1120/orgs",
        reposUrl = "https://api.github.com/users/lkw1120/repos",
        eventsUrl = "https://api.github.com/users/lkw1120/events{/privacy}",
        receivedEventsUrl = "https://api.github.com/users/lkw1120/received_events",
        type = "User",
        siteAdmin = false,
        name = "lkw1120",
        company = null,
        blog = "",
        location = null,
        email = null,
        hireable = null,
        bio = null,
        twitterUsername = null,
        publicRepos = 15,
        publicGists = 8,
        followers = 1,
        following = 7,
        createdAt = "2015-10-21T13:31:33Z",
        updatedAt = "2024-08-10T04:46:15Z"
    )

    fun getUserListResp() = UserListResp(
        totalCount = 1,
        incompleteResults = false,
        items = listOf(
            UserItemResp(
                login = "lkw1120",
                id = 15232122,
                nodeId = "MDQ6VXNlcjE1MjMyMTIy",
                avatarUrl ="https://avatars.githubusercontent.com/u/15232122?v=4",
                gravatarId = "",
                url ="https://api.github.com/users/lkw1120",
                htmlUrl = "https://github.com/lkw1120",
                followersUrl = "https://api.github.com/users/lkw1120/followers",
                followingUrl = "https://api.github.com/users/lkw1120/following{/other_user}",
                gistsUrl = "https://api.github.com/users/lkw1120/gists{/gist_id}",
                starredUrl = "https://api.github.com/users/lkw1120/starred{/owner}{/repo}",
                subscriptionsUrl = "https://api.github.com/users/lkw1120/subscriptions",
                organizationsUrl = "https://api.github.com/users/lkw1120/orgs",
                reposUrl = "https://api.github.com/users/lkw1120/repos",
                eventsUrl = "https://api.github.com/users/lkw1120/events{/privacy}",
                receivedEventsUrl = "https://api.github.com/users/lkw1120/received_events",
                type = "User",
                siteAdmin = false,
                score = 1.0
            )
        )
    )
}